### ISSUE TITLE
Setup a development server copy

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#14]
Suggest we make a copy VM test-academy@ehden.eu to use for development etc.

Is there a preferred way to copy a full course between the servers? Or can we develop on the production server but hide the course for students?

Things like setting up single sign on through Elixer will need to be done on test server

**Comment by lhjohn** [comment]
Copying courses is straight forward using course backups. Those backups can be downloaded and uploaded to other Moodle servers.

I suggest to duplicate the current VM, the same way we did last time with an image, and start up some AWS free tiers with it for testing. More performance will not be necessary.

With such a development server we can also test, whether installing Moodle 3.7 and RemUI 3.7 will break any existing content. RemUI 3.7 has now a homepage builder, which we can maybe  use to make a nice starting page. See [here](https://youtu.be/fTCl587ZREk) and [here](https://edwiser.org/blog/edwiser-remui-3-7-0-released/).

**Comment by PRijnbeek** [comment]
Done we now have test-academy.ehden.eu and academy.ehden.eu servers.
