### ISSUE TITLE
Missing gifs ETL course

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#17]
I see missing gifs:

https://www.test-academy.ehden.eu/course/view.php?id=5

<img width="686" alt="image" src="https://user-images.githubusercontent.com/7252105/60611138-e05fbe80-9dc5-11e9-987c-1972e1316b93.png">

May have to do with the move to test server

**Comment by lhjohn** [comment]
I see these images. This may be a problem with your browser cache. Try opening the course in a private window and let me know if you see the images then.

![Screen Shot 2019-07-03 at 19 43 48](https://user-images.githubusercontent.com/7384198/60613368-0b004600-9dcb-11e9-9e01-7276520f0dfa.png)

**Comment by PRijnbeek** [comment]
No that does not solve the problem, let's have a look together tomorrow.

**Comment by lhjohn** [comment]
Issue resolved.
