### ISSUE TITLE
Remove bitnami Manage on VM

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#18]
<img width="121" alt="image" src="https://user-images.githubusercontent.com/7252105/60611326-5ebc6080-9dc6-11e9-9554-bee8336a473f.png">

They provide instructions for that.

**Comment by lhjohn** [comment]
It should be removed. I ran the following on the server.
`sudo /opt/bitnami/apps/moodle/bnconfig --disable_banner 1`

Once you confirm that you cannot see it anymore we can close this.
