### ISSUE TITLE
CDM course: Feedback form needed

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#23]
We need to add questions in the form. About the prior expertise and some general questions about the content, use of the VM in the course etc.

**Comment by PRijnbeek** [comment]
Created:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/7252105/61182721-9a152580-a637-11e9-8b34-ee497f292eb0.png">

@clairblacketer anything to add/change?

**Comment by lhjohn** [comment]
I would add this multiple choice question:
- The course as a whole was: excellent | very good | good | fair | poor | very poor

**Comment by PRijnbeek** [comment]
i added your question @lhjohn

**Comment by clairblacketer** [comment]
@PRijnbeek I think this looks good, the one thing I can think to add would be a question on any topics they are still confused about or that could have used more instruction
