### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#24]
Are announcements automatically send by email to all students?

**Comment by lhjohn** [comment]
"Announcements" seems to be just a normal Forum. It uses the Forum Activity in Moodle. We technically now have two forums for some courses.

I do not receive a notification when I post into that forum. I also do not see an option to activate it here: https://www.academy.ehden.eu/admin/message.php

**Comment by PRijnbeek** [comment]
I removed it.
