### ISSUE TITLE
Create the Final Exam

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#26]
Find a way to automate this process from a txt file (see doc).

- [x] implement the quiz
- [ ] test the quiz

**Comment by PRijnbeek** [comment]
Quiz is implemented in Moodle. I created a[ GIFT format ](https://docs.moodle.org/37/en/GIFT_format) file that can be upload in the Question Bank in Moodle. That file is in the SharePoint of the course.

@lhjohn can you try do to the quiz. Test the answers randomly. But also answer >80% correct to test you pass the course. Correct answers are shown at the end of test or I have the answer sheet if helpful.

Close the issue if all works fine. We will have others do the test when before we go live.

**Comment by lhjohn** [comment]
Some remarks
- Questions are numbered differently within their title and within the Moodle Quiz
- Questions with many answers enumerate those using strange UTF-8 characters
- Question 25. (24 in the Moodle quiz) should be "multiple answers possible", but is "select single answer"

**Comment by PRijnbeek** [comment]
Thanks.

1) Was only the case for question 24 and 25 order is changed now. I wanted to keep the order as in Patrick's question/answer sheet.

2) Can you give an example?

3) Fixed

**Comment by lhjohn** [comment]
regarding 2: We run out of letters, so Moodle uses strange characters ![letters](https://user-images.githubusercontent.com/7384198/61207824-56cdbc00-a6f6-11e9-84eb-69d05813a6cc.PNG)

We could change the numbering for each questions:
![numbering](https://user-images.githubusercontent.com/7384198/61207880-74028a80-a6f6-11e9-89f9-ecd119d65fc7.PNG)

**Comment by PRijnbeek** [comment]
Which question is that?

**Comment by PRijnbeek** [comment]
Done.
