### ISSUE TITLE
Foundation: Feedback

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#31]
Hi @JellePraet,

It looks good. It is a lot of mainly reading material for the IMI section. Would be nice if we could have a recorded presentation from IMI. We do have he original webinar in which Michel presented the topic that also had a short intro from IMI. It can be useful to explain the process?

I would not refer to the SMEs in the first text box but keep it more general since there will be others in the Academy.

You can also have a look at the CDM course. Here we put the video's as separate lectures.

**Comment by PRijnbeek** [comment]
Jelle we do have the EHDEN presentation from the European OHDSI symposium would that not be useful as a video lecture in the EHDEN section? I think it is more valuable to have a person talk to the slides than show the slide, e.g. why the E in EHDEN etc, why this vision (instead of only showing the vision). The combination would be nice i think.

i suggest to put a bit more instructive text on the pages, for example:

"Here below you can find a webinar of the EHDEN coordinator and lead in which the discuss.....etc"

**Comment by PRijnbeek** [comment]
- [x] Jelle on the Data Partner Catalogue section:

This should be called Database Catalogue not Data Partner Catalogue that is a different thing. Also in the text below do not use Data Catalogue but use Database Catalogue.

**Comment by JellePraet** [comment]
- [x] Hi Peter, Could you add a few lines about the federated network setup (and why we chose it) on the - The EHDEN project -  The EHDEN platform page?

**Comment by JellePraet** [comment]
Solved the issue data partners vs data bases.

**Comment by PRijnbeek** [comment]
Added the text at the platform page. Please review. (i ticked the box above)

**Comment by JellePraet** [comment]
I changed a few typos and "secured environment, **queries** are send to the data, and are run " (you had tools instead of queries)

**Comment by JellePraet** [comment]
I went over all pages and introduced all images and videos a bit better like you suggested. This gives them a bit more context.

**Comment by PRijnbeek** [comment]
We do not send queries to the data actually so much, we run analytical tools locally.

**Comment by JellePraet** [comment]
I've filled in a short header for the course and the 3 sections and added all sources I've used when putting the course together.

**Comment by JellePraet** [comment]
> 
> 
> We do not send queries to the data actually so much, we run analytical tools locally.

Ok. Reverted it back to tools..
