### ISSUE TITLE
Foundation: add IMI Webinar

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#32]
Suggest we add this Webinar in the IMI section:

https://www.imi.europa.eu/news-events/events/webinars-imi2-calls-11-12

It has a nice introduction on IMI as well in it and it is nice to show as this is how EHDN started.

We can then also add my presentation at OHDSI Europe that explains how we got to EHDEN etc

We can download it including the slide deck

**Comment by JellePraet** [comment]
I emailed IMI for the recording as you can't download it directly (you have to register and then you can only watch it).

@PRijnbeek  Send me your slide deck and I'll add it.

**Comment by PRijnbeek** [comment]
We have video's from OHDSI. I actually think all are relevant. @lhjohn i placed the video file here of the full day and the pdfs for Jelle. Can you cut all the sections  according to the pdfs (for example the EHDEN part as separate video's) and add the slide in front with the title and speaker name see also https://www.ohdsi-europe.org/index.php/symposium-2019 for their names.

**Comment by PRijnbeek** [comment]
@JellePraet We can get this video from their site as well by recording a gotomeeting while playing the video can take some time to get this from IMI

**Comment by JellePraet** [comment]
I prefer if they send us the real recording :) If I don't hear back by Tuesday, then I'll fix it by recording my screen and audio while it's playing.

**Comment by lhjohn** [comment]
The videos can be found [here](https://synapsemanagers.sharepoint.com/:f:/r/sites/EHDEN/Academy/Foundations/Shared%20Documents/Videos?csf=1&e=GHJSj2).

I believe I have not seen the presentations "OHDSI in Action" and "Lightning Talks" in those videos.
