### ISSUE TITLE
Academy Support: Update Logo

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#33]
@JellePraet i have created this course logo:

![Academy](https://user-images.githubusercontent.com/7252105/61594102-01a71400-abe8-11e9-9d7b-88990b73016b.png)

I need two things:

- [x] Vector version of the hat
- [x] What is the font type we use on our logo.

**Comment by JellePraet** [comment]
I can't see which font the developper used in the original image files, but at whatthefont.com you can upload an image to find out what font it is and 'Wedding Gothic ATF Bold' seems like it's a 100% match. 

I'll email the vector version in a minute.
