### ISSUE TITLE
Academy Support: add videos to course

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#34]
@lhjohn if have added a premiere file that is fully edited and the recorded source mp4 in the Academy sharepoint.

For some reason my Premiere will not render the file for me can you try in your version.

I have added two clips. One that has all in one and another clip that has all the lectures with black in between. Can you render the last one per lecture and add your slide with the title for each.

You can then add them to the course.

The last part relevant for the SMEs we will add based on recordings of the SME TCs this week.

**Comment by lhjohn** [comment]
I get the error: This project was saved in a newer version of Adobe Premier Pro and cannot be opened in this version.

**Comment by lhjohn** [comment]
Done.
