### ISSUE TITLE
Foundation: Add European OHDSI videos

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#35]
@lhjohn i added a section that will host the videos you rendered last week. Can you add these as video lectures.

We can meet briefly tomorrow to discuss the details.

We can close this issue once this section is final.

**Comment by lhjohn** [comment]
Done.

**Comment by PRijnbeek** [comment]
Henrik which videos where you missing exactly? than I can ask for them.

**Comment by lhjohn** [comment]
These are missing:
- Lightning Talks of selected abstracts (Moderator: Kristin Kostka,)
- Data to Evidence: OHDSI in action! (Patrick Ryan)
(- Closing Remarks)

**Comment by PRijnbeek** [comment]
Requested these from AV team. Not critical for the milestone, so removed it.

**Comment by PRijnbeek** [comment]
They are available now, do you still want to add them or shall we add them in round 2?
