### ISSUE TITLE
Foundation: BD4BO Graphic Incorrect

### ISSUE THREAD

**Issue by nigehughes** [EHDEN/Academy#45]
In https://www.academy.ehden.eu/mod/lesson/view.php?id=123&pageid=45 the graphic used has been prior discussed as incorrect for EHDEN (outcomes sets and demonstrating value not included)

**Comment by JellePraet** [comment]
Removed the image and adjust the text to reflect this.

I suggest that, once Nigel and myself are both back in the office in September, we do a thorough review of the slide library just like we've done last month for the website. I can put the image back in after that? It's not so critical to the story anyway... ? During August, i'll start working on a draft update of the slide library.

**Comment by nigehughes** [comment]
Hi Jelle

Agreed - not crucial now, and a corrected version can be reinstated once we have reviewed the slide library.
