### ISSUE TITLE
Dashboard, 'Add Note' function seems to redirect outside of EHDEN academy

### ISSUE THREAD

**Issue by pbr6cornell** [EHDEN/Academy#46]

**Comment by pbr6cornell** [comment]
I'm not sure the 'Add Notes' function on the user dashboard is necessary, but if it is desired, note that when you click 'Add personal notes', the website attempts to redirect outside of academy then fails.

It appears to be a permission issue, but I suspect that may be also issue for SME?

![image](https://user-images.githubusercontent.com/731930/62009684-22172700-b130-11e9-97e2-639bad94af36.png)

**Comment by PRijnbeek** [comment]
I am also not convinced it will be used. This is now switched off and not visible anymore. (Site administration-> search for notes-> switch off and also switch RemUI block off.
