### ISSUE TITLE
ETL:  Text Suggestions

### ISSUE THREAD

**Issue by ericaVoss** [EHDEN/Academy#47]
- _"What is the importance of the Common Data Model, why would I want to transform my data into this structure and what tools are available to me?"_
What is the importance of the Common Data Model? Why would I want to transform my data into this structure?  What tools are available to help me through this process?

- Why CDM?  _"For this portion of the lesson you can choose either to watch a video or to go through self-lead content. To choose video click the button on the bottom left, to choose self-guided choose the button on the bottom right."_
For this portion of the lesson you can choose either to watch a video or to go through self-guided content. To choose video click the button on the bottom left, to choose self-guided choose the button on the bottom right. 

- Why CDM?  What the ETL process looks like - font randomly gets larger in second paragraph.

- Setup for the lesson _"Rabbit-in-a-Hat: A tool that works with the White Rabbit scan information to facilitate the documentation of source to CDM mapping logic."_
Rabbit-in-a-Hat: A tool that comes with the White Rabbit tool, works with the White Rabbit scan information to facilitate the documentation of source to CDM mapping logic.

- Setup for the lesson - just link out to Lauren Data, figure it is enough of a citation.
https://www.endometriosis-uk.org/laurens-surgery-story

- White Rabbit - should we consistently make it one word?  WhiteRabbit?

- The Submission Status on "Vocabulary mapping Assignment" says "Assignment is overdue by: 18 days 20 hours"

- Maybe in the final example redirect them to some of the key links, like the CDM Wiki and WhiteRabbit Wiki

- Course Feedback - "Did you miss any content in the course?"
I think this is meant to read:
Was there content difficult to understand?

**Comment by PRijnbeek** [comment]
@clairblacketer you can fix this the ETL course will not be opened today but in max 2 weeks from now.

**Comment by clairblacketer** [comment]
Done! Thanks @ericaVoss for the thorough feedback!
