### ISSUE TITLE
Course icons on Course Archive Section

### ISSUE THREAD

**Issue by solventrix** [EHDEN/Academy#48]
Text in the course icons is too large to be properly displayed
![archive overview](https://user-images.githubusercontent.com/4600687/62027581-50ebd680-b1de-11e9-8ca4-ad98227c5de3.PNG)

**Comment by PRijnbeek** [comment]
Fixed by make images smaller.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/7252105/62040381-cfa23d00-b1f9-11e9-8298-ac55dbec9f73.png">
