### ISSUE TITLE
Academy Instructions Document: Typo's

### ISSUE THREAD

**Issue by Jbakx** [EHDEN/Academy#49]
**1. INTRODUCTION**
_The Academy uses Moodle (www.moodle.org) as a framework that is
being populated with multiple **course**._   -->  course should be plural

_Initially, the focus is on Small to Medium-sized Enterprises (SMEs) that can obtain certification for standardising health data to the OMOP Common Data Model **ad** setting up the local analytical framework._  --> and

**2. SETUP**
_If you think you should have access but do not have **it let** us know by sending an email to academy@ehden.eu_  --> I think there should be a comma

_The following login screen will be **shows:**_  --> shown

_At the moment you can only login with the provided Username and **Password, however**, we will enable Authentication through third party providers such as Elixer AAI, Github, and will enable Single Sign On (SSO)._  --> I think this should be a new sentence

_(do not click on Edit Profile next to **Courses this** is only a subset of the profile)_  --> Courses, since this...

_This will open a larger form where you can fill in all the information **you like** to share_  --> I think it's better to say 'you would like to share'

_For SMEs that participate in the training and certification program please also fill in the Company Name under **"Other fields**_.  --> "Other fields".

_In the user menu (top right) under preferences you can setup how you like to interact with the **forum for** example if you like to receive emails._  --> I think there should be a comma 

_In the user menu (top right) under preferences you can setup how you like to interact with the forum for example if **you like** to receive emails._  --> you would like 

_Some of these are **switch on** by default, e.g. notifications about forum posts._  --> switched on

**3. COURSES**
_**Courses contains section**, e.g. The Foundations of OHDSI section show in Figure 6. These contain lectures and quizzes._  --> Courses contain sections

_The sections can contain multiple-choice questions in the form of quizzes or **exercise** the user has to perform on actual data using the OHDSI-IN-A-BOX virtual machine as described in more detail below._  --> plural (exercises)

_Instructions on how to pass a course **should be provided** on the course introduction page and at each individual assessment page._  --> are provided (?)

**4. OHDSI-IN-A-BOX**
_It contains many OHDSI **tool,** a CDM database with simulated data and a source database that can be used in the EHDEN Academy to train on mapping._  --> plural (tools)

**Comment by PRijnbeek** [comment]
Thanks all have been updated and new pdf is in available in the course.
