### ISSUE TITLE
My courses sub-menu 

### ISSUE THREAD

**Issue by Jbakx** [EHDEN/Academy#50]
When clicking the arrow next to 'My Courses' in the menu on the left side of the screen, the sub-menu opens as it's supposed to. However, when I click on the tab 'My Courses' (and not the arrow), it opens the sub-menu while it loads the 'my courses' page, after which the submenu closes again. I think the submenu isn't supposed to open when just clicking the tab? 

![submenu](https://user-images.githubusercontent.com/50862985/62039070-3d993500-b1f7-11e9-86d1-eb72937add39.png)

**Comment by PRijnbeek** [comment]
Not sure what you mean. Seems to work fine for me. If you click on "My Courses" the pages opens. When you click on the arrow the submenu opens.

This not something we can change it is part of the template.
