### ISSUE TITLE
ETL: Rabbit in a Hat Observation Period video not working

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#51]
Dani report  he  has watched the videos on an iPad (new iPad Pro) and everything run well with only one exception: the Rabbit in A Hat - Mapping Example - OBSERVATION_PERIOD video did not charge for some reason. I tried logging out and in, refreshing the page etc and this did not fix the issue. I wonder whether the format of this video has something special?

![image](https://user-images.githubusercontent.com/7252105/62040827-a0400000-b1fa-11e9-9cab-8b93ea571f49.png)

Part of the ETL course no priority now.

**Comment by clairblacketer** [comment]
@PRijnbeek I will take a look, it might have something to do with how the video is being referenced in the course.

**Comment by clairblacketer** [comment]
Should be fixed now :)
