### ISSUE TITLE
CDM Final Exam: typos and suggestions

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/Academy#52]
https://www.academy.ehden.eu/mod/quiz/attempt.php?attempt=104&cmid=111&page=11

## Typos and other objective issues

- [x] Q11+12: both state 'What is a difference ...' in the question, but multiple answers are right. Replace by 'What are differences ...'
- [x] Q21: `drug_exposure_end_date can be empty` In v6 the date is not required, but the datetime field is required. 
- [x] Q24: typo, visit_occurence --> visit_occurRence
- [x] Q25: `fields needed for length of visit` Should allow multiple answers. Also, I do not agree with the current correct 'one' answer, which is not a field (9201 - Inpatient Visit). -> correct that one should have been -100%
- [x] Q30: contains some residual characters: '_____{'

## Suggestions
 - [x] We need to specify the OMOP CDM version which the test is about somewhere. Or did I miss this?
 - [x] Allow just one answer (radio buttons) for questions that clearly have one right answer. This might make things a bit clearer. Questions 4-5, 8-10, 26-41 -> agree but this means you have to understand it even better.

## Subjective remarks
 - [x] Q2+3: The vocab tables are easily missed in the long list. Either list all vocab tables at the end in sequence, add one option stating simply 'All vocabulary tables' or remove them from the list. Tables are now easily missed, causing some frustration. -> agree but we will keep it as is so they know which are vocabulary tables.
 - [x] Q5: `What should be used to populate a required CONCEPT_ID field if the true value is unmapped or unknown?` Needs some nuance; in some cases an answer is recorded as 'unknown', which has to be mapped as a literal unknown. e.g. an unknown tobacco status (4141786). Suggestion: change the question to reflect '...if the true value is unmapped _or not given._'
 - [ x] Q16: `If my source data has extra information that doesn’t fit in the OMOP CDM, I should add fields to existing tables or add my own tables`. Again, more nuanced option needed, e.g. 'No, I should search first for existing initiatives in the OHDSI community and start a community discussion on this if there is no initiative yet'.
 - [x ] Q29: `If a ... how can the CONDITION_SOURCE_VALUE field be populated?`. I like that it is a trick question, but almost impossible to get right. Please add the option 'Every value is possible, but 410.91 is preferred', to give people a chance to get it right. -> we will keep as is and check who got it right.
   - [x] In addition: put emphasis on the '**how can**' and use the 'how should' consistently in the other questions (Q27,28,30 also use 'how can').
 - [x] Q32: Same as for Q29. Give the option for 'This table should not be populated'

Sorry for the long list, I do not exclude that this is because I just barely passed the test 😄 (32.4 out of 40 where 32 was required).

**Comment by PRijnbeek** [comment]
Thanks Maxim we will process these and respond to each here.

We will open the CDM + Vocab next week so perfectly in time these suggestions.

Good you passed ;)

**Comment by PRijnbeek** [comment]
Maxim i changed most of them or explained why not.
