### ISSUE TITLE
Foundation: missing figure

### ISSUE THREAD

**Issue by Jbakx** [EHDEN/Academy#54]
On the page EHDEN Foundation --> General introduction to IMI --> Public-Private Partners
(https://www.academy.ehden.eu/mod/lesson/view.php?id=117&pageid=35&startlastseen=no) it says 'Figure 2' while there is no figure visible

![PPP figure EHDEN Academy](https://user-images.githubusercontent.com/50862985/62274250-cbfff780-b43f-11e9-987c-4eb3e575d2a2.png)

**Comment by JellePraet** [comment]
Fixed. Was a copy paste error as there was indeed no figure :)
