### ISSUE TITLE
CDM: Vocabulary Quiz typo's and suggestions

### ISSUE THREAD

**Issue by Jbakx** [EHDEN/Academy#56]
Some suggestions for the CDM Vocabulary Quiz

**Question 7**: Answer a is out of line due to a bullet point
**Question 8**: Image too big and therefore out of margin
**Question 8**: Typo: concept_relationshop 
**Question 10**: Typo: period at the end of the second sentence

**Comment by lhjohn** [comment]
Thanks for the feedback, all fixed.
