### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Academy#69]
We are not allowed to change the colors of the imi logo etc please change to a white box

**Comment by lhjohn** [comment]
There are websites that use the white logos, such as this one https://www.beat-dkd.eu in the footer.

Also the official IMI website has the white logos in its footer: https://www.imi.europa.eu.

I think it would look significantly better if we could use white logos.

**Comment by lhjohn** [comment]
Ok, so the IMI logo can officially be used in white according to these logo guidelines on page 19: https://www.imi.europa.eu/sites/default/files/archive/uploads/documents/IMICorporateDesignManual2014Web.pdf

EU logo guidelines: http://publications.europa.eu/code/en/en-5000100.htm

**Comment by lhjohn** [comment]
I have now created a white box with the original logos.

If there is time in the future we can look into using white logos, but it seems like we need to ask permission even for using the official white logos.

**Comment by PRijnbeek** [comment]
I was not aware of these white logos. If they have them we are allowed to use them.

**Comment by PRijnbeek** [comment]
By the way do not use the Red color on the home page please:

![image](https://user-images.githubusercontent.com/7252105/75110981-0c6dcf80-5635-11ea-9eba-b92e017fbe0d.png)

**Comment by lhjohn** [comment]
The red color is only temporary as it helps me to distinguish the production and development site more easily when transferring settings. I will change it back to the blue shortly.

**Comment by PRijnbeek** [comment]
I understand keep the red if that is easier for you.
