### ISSUE TITLE
Feedback Course 5 - Extract, Transform and Load

### ISSUE THREAD

**Issue by lhjohn** [EHDEN/Academy#73]
Original Feedback: [ETL Feedback.zip](https://github.com/EHDEN/Academy/files/4270109/ETL.Feedback.zip)

**Comment by clairblacketer** [comment]
Thanks - I will take a look at this.

**Comment by clairblacketer** [comment]
I made changes to the course exam based on feedback. Some of the larger changes that were requested were not in scope for this round.
