### ISSUE TITLE
Reserve additional URL https://ehdenacademy.eu

### ISSUE THREAD

**Issue by lhjohn** [EHDEN/Academy#80]
Is it possible to reserve the additional URL https://ehdenacademy.eu, which automatically forwards to https://academy.ehden.eu?

Or can we only reserve ehden.eu domains?

To the outside, this URL (https://ehdenacademy.eu) may be easier to remember and search for if you have only heard the name 'EHDEN Academy' in a conversation.

**Comment by PRijnbeek** [comment]
we  could but I think google will solve this problem for us already

**Comment by lhjohn** [comment]
Agree
