### ISSUE TITLE
AR - Research if there is a Moodle API

### ISSUE THREAD

**Issue by lhjohn** [EHDEN/Academy#88]
To implement the count-up widget we need to get the current number of users from the Moodle site. Find out if there is a Moodle API that could be queried for this.

**Comment by sdotter** [comment]
yeah there is... i've just checked it and there are API calls we can use from moodle.
Just curl / fetching calls to the backend (https://docs.moodle.org/dev/Core_APIs)
But also possible to directly query the database:

![image](https://user-images.githubusercontent.com/11946839/160367639-003703bb-ca67-40df-8ea8-24a23a5be4e6.png)
